### ISSUE TITLE
Any metadata?

### ISSUE THREAD

**Issue by ogencoglu** [lukefeilberg/onion#1]
Thanks for the dataset!

Is there any metadata such as date, url and source (for 0 labels) of the articles?

**Comment by lukefeilberg** [comment]
I only collected the titles. If you go through my Jupyter Notebook I
outline how I got the data using the Reddit Pushshift API. I believe it
wouldn’t be too hard to modify my code to get the links in each post (aka
the source) as well as the date of the posts, but getting the dates of the
articles themselves may require actually scraping them.

Good luck!

Luke Feilberg
